//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://edisoftwebservices.com/", ConfigurationName="ShipmentExporterEntryPointSoap")]
public interface ShipmentExporterEntryPointSoap
{
    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://edisoftwebservices.com/GetShipmentByShipmentNumber", ReplyAction = "*")]
    System.IAsyncResult BeginGetShipmentByShipmentNumber(string userName, string password, string installationValue, int[] actors, string shipmentNumber, System.AsyncCallback callback, object asyncState);
    
    Response EndGetShipmentByShipmentNumber(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://edisoftwebservices.com/GetShipmentByOrderNumber", ReplyAction = "*")]
    System.IAsyncResult BeginGetShipmentByOrderNumber(string userName, string password, string installationValue, int[] actors, string referenceNumber, System.AsyncCallback callback, object asyncState);
    
    Response EndGetShipmentByOrderNumber(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://edisoftwebservices.com/GetShipmentsByOrderNumber", ReplyAction = "*")]
    System.IAsyncResult BeginGetShipmentsByOrderNumber(string userName, string password, string installationValue, int[] actors, string referenceNumber, System.AsyncCallback callback, object asyncState);
    
    Response EndGetShipmentsByOrderNumber(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://edisoftwebservices.com/GetShipmentByPackageNumber", ReplyAction = "*")]
    System.IAsyncResult BeginGetShipmentByPackageNumber(string userName, string password, string installationValue, int[] actors, string packageNumber, System.AsyncCallback callback, object asyncState);
    
    Response EndGetShipmentByPackageNumber(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://edisoftwebservices.com/GetShipmentByDateRange", ReplyAction = "*")]
    System.IAsyncResult BeginGetShipmentByDateRange(string userName, string password, string installationValue, int[] actors, System.DateTime startDate, System.DateTime endDate, int pageIndex, System.AsyncCallback callback, object asyncState);
    
    Response EndGetShipmentByDateRange(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://edisoftwebservices.com/GetEvents", ReplyAction = "*")]
    System.IAsyncResult BeginGetEvents(string userName, string password, System.DateTime eventDateTimeStart, System.DateTime eventDateTimeEnd, System.AsyncCallback callback, object asyncState);
    
    EventResponse EndGetEvents(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://edisoftwebservices.com/GetEventsByEventCode", ReplyAction = "*")]
    System.IAsyncResult BeginGetEventsByEventCode(string userName, string password, System.DateTime eventDateTimeStart, System.DateTime eventDateTimeEnd, string[] eventCode, int[] actorId, System.AsyncCallback callback, object asyncState);
    
    EventResponseByEvent EndGetEventsByEventCode(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://edisoftwebservices.com/VerifyCount", ReplyAction = "*")]
    System.IAsyncResult BeginVerifyCount(string userName, string password, System.DateTime eventDateTimeStart, System.DateTime eventDateTimeEnd, string[] eventCode, int[] actorId, System.AsyncCallback callback, object asyncState);
    
    EventCountResponse EndVerifyCount(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://edisoftwebservices.com/GetShipmentStatus", ReplyAction = "*")]
    System.IAsyncResult BeginGetShipmentStatus(string userName, string password, string number, System.AsyncCallback callback, object asyncState);
    
    EventResponse EndGetShipmentStatus(System.IAsyncResult result);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class Response
{
    
    private ShipmentDto[] shipmentsField;
    
    private ResponseStatus responseStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public ShipmentDto[] Shipments
    {
        get
        {
            return this.shipmentsField;
        }
        set
        {
            this.shipmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ResponseStatus ResponseStatus
    {
        get
        {
            return this.responseStatusField;
        }
        set
        {
            this.responseStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class ShipmentDto : GenericEntityDto
{
    
    private string shipmentNumberField;
    
    private string orderNumberField;
    
    private string carrierNameField;
    
    private string productNameField;
    
    private System.DateTime timeStampField;
    
    private System.Nullable<System.DateTime> dateSubmittedField;
    
    private int shipmentClientIdField;
    
    private string userField;
    
    private string lastStatusField;
    
    private PackageDto[] packagesField;
    
    private ReferenceDto[] shipmentReferencesField;
    
    private AmountDto[] amountsField;
    
    private CarrierMeasurement[] carrierMeasurementsField;
    
    private TrackAndTraceDto[] trackAndTraceListField;
    
    private SenderDto senderField;
    
    private ReceiverDto receiverField;
    
    private PickupDto pickupField;
    
    private PayerDto payerField;
    
    private BuyerDto buyerField;
    
    private TemporaryDto temporaryField;
    
    private MessageDto messageField;
    
    private ForwarderDto forwarderField;
    
    private ReturnToDto returnToField;
    
    private DropPointDto dropPointField;
    
    private DepotDto depotField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string ShipmentNumber
    {
        get
        {
            return this.shipmentNumberField;
        }
        set
        {
            this.shipmentNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string OrderNumber
    {
        get
        {
            return this.orderNumberField;
        }
        set
        {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string CarrierName
    {
        get
        {
            return this.carrierNameField;
        }
        set
        {
            this.carrierNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string ProductName
    {
        get
        {
            return this.productNameField;
        }
        set
        {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public System.DateTime TimeStamp
    {
        get
        {
            return this.timeStampField;
        }
        set
        {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
    public System.Nullable<System.DateTime> DateSubmitted
    {
        get
        {
            return this.dateSubmittedField;
        }
        set
        {
            this.dateSubmittedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public int ShipmentClientId
    {
        get
        {
            return this.shipmentClientIdField;
        }
        set
        {
            this.shipmentClientIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string LastStatus
    {
        get
        {
            return this.lastStatusField;
        }
        set
        {
            this.lastStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
    public PackageDto[] Packages
    {
        get
        {
            return this.packagesField;
        }
        set
        {
            this.packagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
    public ReferenceDto[] ShipmentReferences
    {
        get
        {
            return this.shipmentReferencesField;
        }
        set
        {
            this.shipmentReferencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
    public AmountDto[] Amounts
    {
        get
        {
            return this.amountsField;
        }
        set
        {
            this.amountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
    public CarrierMeasurement[] CarrierMeasurements
    {
        get
        {
            return this.carrierMeasurementsField;
        }
        set
        {
            this.carrierMeasurementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
    public TrackAndTraceDto[] TrackAndTraceList
    {
        get
        {
            return this.trackAndTraceListField;
        }
        set
        {
            this.trackAndTraceListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public SenderDto Sender
    {
        get
        {
            return this.senderField;
        }
        set
        {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=15)]
    public ReceiverDto Receiver
    {
        get
        {
            return this.receiverField;
        }
        set
        {
            this.receiverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=16)]
    public PickupDto Pickup
    {
        get
        {
            return this.pickupField;
        }
        set
        {
            this.pickupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public PayerDto Payer
    {
        get
        {
            return this.payerField;
        }
        set
        {
            this.payerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=18)]
    public BuyerDto Buyer
    {
        get
        {
            return this.buyerField;
        }
        set
        {
            this.buyerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=19)]
    public TemporaryDto Temporary
    {
        get
        {
            return this.temporaryField;
        }
        set
        {
            this.temporaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=20)]
    public MessageDto Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=21)]
    public ForwarderDto Forwarder
    {
        get
        {
            return this.forwarderField;
        }
        set
        {
            this.forwarderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=22)]
    public ReturnToDto ReturnTo
    {
        get
        {
            return this.returnToField;
        }
        set
        {
            this.returnToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=23)]
    public DropPointDto DropPoint
    {
        get
        {
            return this.dropPointField;
        }
        set
        {
            this.dropPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=24)]
    public DepotDto Depot
    {
        get
        {
            return this.depotField;
        }
        set
        {
            this.depotField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class PackageDto : GenericEntityDto
{
    
    private CarrierMeasurement[] carrierMeasurementsField;
    
    private TrackAndTraceDto[] trackAndTraceListField;
    
    private string packageNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public CarrierMeasurement[] CarrierMeasurements
    {
        get
        {
            return this.carrierMeasurementsField;
        }
        set
        {
            this.carrierMeasurementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    public TrackAndTraceDto[] TrackAndTraceList
    {
        get
        {
            return this.trackAndTraceListField;
        }
        set
        {
            this.trackAndTraceListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string PackageNumber
    {
        get
        {
            return this.packageNumberField;
        }
        set
        {
            this.packageNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class CarrierMeasurement : GenericEntityDto
{
    
    private double volumeField;
    
    private double priceField;
    
    private string priceCurrencyField;
    
    private int weightGField;
    
    private string awbField;
    
    private string orderNumberField;
    
    private bool isShipmentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public double Volume
    {
        get
        {
            return this.volumeField;
        }
        set
        {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public double Price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string PriceCurrency
    {
        get
        {
            return this.priceCurrencyField;
        }
        set
        {
            this.priceCurrencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int WeightG
    {
        get
        {
            return this.weightGField;
        }
        set
        {
            this.weightGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Awb
    {
        get
        {
            return this.awbField;
        }
        set
        {
            this.awbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string OrderNumber
    {
        get
        {
            return this.orderNumberField;
        }
        set
        {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public bool IsShipment
    {
        get
        {
            return this.isShipmentField;
        }
        set
        {
            this.isShipmentField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsignorEventDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DepotDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DropPointDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnToDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ForwarderDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TemporaryDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BuyerDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PayerDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PickupDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiverDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SenderDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AmountDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackAndTraceDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CarrierMeasurement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PackageDto))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShipmentDto))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public abstract partial class GenericEntityDto
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class EventCountResponse
{
    
    private int countField;
    
    private ResponseStatus responseStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ResponseStatus ResponseStatus
    {
        get
        {
            return this.responseStatusField;
        }
        set
        {
            this.responseStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class ResponseStatus
{
    
    private string statusCodeField;
    
    private string statusDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string StatusCode
    {
        get
        {
            return this.statusCodeField;
        }
        set
        {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StatusDescription
    {
        get
        {
            return this.statusDescriptionField;
        }
        set
        {
            this.statusDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class EventResponseByEvent
{
    
    private GenericEntityDto[] eventsField;
    
    private ResponseStatus responseStatusField;
    
    private System.DateTime startDateField;
    
    private System.DateTime endDateField;
    
    private string[] eventCodesField;
    
    private int[] actorIdsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(typeof(CarrierMeasurement))]
    [System.Xml.Serialization.XmlArrayItemAttribute(typeof(ConsignorEventDto))]
    [System.Xml.Serialization.XmlArrayItemAttribute(typeof(TrackAndTraceDto))]
    public GenericEntityDto[] Events
    {
        get
        {
            return this.eventsField;
        }
        set
        {
            this.eventsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ResponseStatus ResponseStatus
    {
        get
        {
            return this.responseStatusField;
        }
        set
        {
            this.responseStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime StartDate
    {
        get
        {
            return this.startDateField;
        }
        set
        {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime EndDate
    {
        get
        {
            return this.endDateField;
        }
        set
        {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
    public string[] EventCodes
    {
        get
        {
            return this.eventCodesField;
        }
        set
        {
            this.eventCodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
    public int[] ActorIds
    {
        get
        {
            return this.actorIdsField;
        }
        set
        {
            this.actorIdsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class ConsignorEventDto : GenericEntityDto
{
    
    private string nameField;
    
    private string eventCodeField;
    
    private System.DateTime eventDateTimeField;
    
    private string awbField;
    
    private string orderNumberField;
    
    private bool isShipmentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string EventCode
    {
        get
        {
            return this.eventCodeField;
        }
        set
        {
            this.eventCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime EventDateTime
    {
        get
        {
            return this.eventDateTimeField;
        }
        set
        {
            this.eventDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Awb
    {
        get
        {
            return this.awbField;
        }
        set
        {
            this.awbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string OrderNumber
    {
        get
        {
            return this.orderNumberField;
        }
        set
        {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public bool IsShipment
    {
        get
        {
            return this.isShipmentField;
        }
        set
        {
            this.isShipmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class TrackAndTraceDto : GenericEntityDto
{
    
    private string nameField;
    
    private string postalCodeField;
    
    private string eventCodeField;
    
    private System.DateTime eventDateTimeField;
    
    private string locationField;
    
    private string awbField;
    
    private string orderNumberField;
    
    private bool isShipmentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string EventCode
    {
        get
        {
            return this.eventCodeField;
        }
        set
        {
            this.eventCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime EventDateTime
    {
        get
        {
            return this.eventDateTimeField;
        }
        set
        {
            this.eventDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Awb
    {
        get
        {
            return this.awbField;
        }
        set
        {
            this.awbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string OrderNumber
    {
        get
        {
            return this.orderNumberField;
        }
        set
        {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public bool IsShipment
    {
        get
        {
            return this.isShipmentField;
        }
        set
        {
            this.isShipmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class EventResponse
{
    
    private GenericEntityDto[] eventsField;
    
    private ResponseStatus responseStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(typeof(CarrierMeasurement))]
    [System.Xml.Serialization.XmlArrayItemAttribute(typeof(ConsignorEventDto))]
    [System.Xml.Serialization.XmlArrayItemAttribute(typeof(TrackAndTraceDto))]
    public GenericEntityDto[] Events
    {
        get
        {
            return this.eventsField;
        }
        set
        {
            this.eventsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ResponseStatus ResponseStatus
    {
        get
        {
            return this.responseStatusField;
        }
        set
        {
            this.responseStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class DepotDto : GenericEntityDto
{
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string name1Field;
    
    private string name2Field;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class DropPointDto : GenericEntityDto
{
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string name1Field;
    
    private string name2Field;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class ReturnToDto : GenericEntityDto
{
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string name1Field;
    
    private string name2Field;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class ForwarderDto : GenericEntityDto
{
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string name1Field;
    
    private string name2Field;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class MessageDto : GenericEntityDto
{
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string name1Field;
    
    private string name2Field;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class TemporaryDto : GenericEntityDto
{
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string name1Field;
    
    private string name2Field;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class BuyerDto : GenericEntityDto
{
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string name1Field;
    
    private string name2Field;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class PayerDto : GenericEntityDto
{
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string name1Field;
    
    private string name2Field;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class PickupDto : GenericEntityDto
{
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string name1Field;
    
    private string name2Field;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class ReceiverDto : GenericEntityDto
{
    
    private string name1Field;
    
    private string name2Field;
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string receiverCustomerNumberField;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string ReceiverCustomerNumber
    {
        get
        {
            return this.receiverCustomerNumberField;
        }
        set
        {
            this.receiverCustomerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class SenderDto : GenericEntityDto
{
    
    private string name1Field;
    
    private string name2Field;
    
    private string postalCodeField;
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string phoneField;
    
    private string cityField;
    
    private string countryIsoField;
    
    private string attentionField;
    
    private string mobileField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name1
    {
        get
        {
            return this.name1Field;
        }
        set
        {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Name2
    {
        get
        {
            return this.name2Field;
        }
        set
        {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string StreetAddress1
    {
        get
        {
            return this.streetAddress1Field;
        }
        set
        {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string StreetAddress2
    {
        get
        {
            return this.streetAddress2Field;
        }
        set
        {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string CountryIso
    {
        get
        {
            return this.countryIsoField;
        }
        set
        {
            this.countryIsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class AmountDto : GenericEntityDto
{
    
    private string nameField;
    
    private double valueField;
    
    private string currencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public double Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edisoftwebservices.com/")]
public partial class ReferenceDto : GenericEntityDto
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ShipmentExporterEntryPointSoapChannel : ShipmentExporterEntryPointSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ShipmentExporterEntryPointSoapClient : System.ServiceModel.ClientBase<ShipmentExporterEntryPointSoap>, ShipmentExporterEntryPointSoap
{
    
    public ShipmentExporterEntryPointSoapClient()
    {
    }
    
    public ShipmentExporterEntryPointSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ShipmentExporterEntryPointSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipmentExporterEntryPointSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipmentExporterEntryPointSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Response GetShipmentByShipmentNumber(string userName, string password, string installationValue, int[] actors, string shipmentNumber)
    {
        return base.Channel.GetShipmentByShipmentNumber(userName, password, installationValue, actors, shipmentNumber);
    }
    
    public System.IAsyncResult BeginGetShipmentByShipmentNumber(string userName, string password, string installationValue, int[] actors, string shipmentNumber, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetShipmentByShipmentNumber(userName, password, installationValue, actors, shipmentNumber, callback, asyncState);
    }
    
    public Response EndGetShipmentByShipmentNumber(System.IAsyncResult result)
    {
        return base.Channel.EndGetShipmentByShipmentNumber(result);
    }
    
    public Response GetShipmentByOrderNumber(string userName, string password, string installationValue, int[] actors, string referenceNumber)
    {
        return base.Channel.GetShipmentByOrderNumber(userName, password, installationValue, actors, referenceNumber);
    }
    
    public System.IAsyncResult BeginGetShipmentByOrderNumber(string userName, string password, string installationValue, int[] actors, string referenceNumber, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetShipmentByOrderNumber(userName, password, installationValue, actors, referenceNumber, callback, asyncState);
    }
    
    public Response EndGetShipmentByOrderNumber(System.IAsyncResult result)
    {
        return base.Channel.EndGetShipmentByOrderNumber(result);
    }
    
    public Response GetShipmentsByOrderNumber(string userName, string password, string installationValue, int[] actors, string referenceNumber)
    {
        return base.Channel.GetShipmentsByOrderNumber(userName, password, installationValue, actors, referenceNumber);
    }
    
    public System.IAsyncResult BeginGetShipmentsByOrderNumber(string userName, string password, string installationValue, int[] actors, string referenceNumber, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetShipmentsByOrderNumber(userName, password, installationValue, actors, referenceNumber, callback, asyncState);
    }
    
    public Response EndGetShipmentsByOrderNumber(System.IAsyncResult result)
    {
        return base.Channel.EndGetShipmentsByOrderNumber(result);
    }
    
    public Response GetShipmentByPackageNumber(string userName, string password, string installationValue, int[] actors, string packageNumber)
    {
        return base.Channel.GetShipmentByPackageNumber(userName, password, installationValue, actors, packageNumber);
    }
    
    public System.IAsyncResult BeginGetShipmentByPackageNumber(string userName, string password, string installationValue, int[] actors, string packageNumber, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetShipmentByPackageNumber(userName, password, installationValue, actors, packageNumber, callback, asyncState);
    }
    
    public Response EndGetShipmentByPackageNumber(System.IAsyncResult result)
    {
        return base.Channel.EndGetShipmentByPackageNumber(result);
    }
    
    public Response GetShipmentByDateRange(string userName, string password, string installationValue, int[] actors, System.DateTime startDate, System.DateTime endDate, int pageIndex)
    {
        return base.Channel.GetShipmentByDateRange(userName, password, installationValue, actors, startDate, endDate, pageIndex);
    }
    
    public System.IAsyncResult BeginGetShipmentByDateRange(string userName, string password, string installationValue, int[] actors, System.DateTime startDate, System.DateTime endDate, int pageIndex, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetShipmentByDateRange(userName, password, installationValue, actors, startDate, endDate, pageIndex, callback, asyncState);
    }
    
    public Response EndGetShipmentByDateRange(System.IAsyncResult result)
    {
        return base.Channel.EndGetShipmentByDateRange(result);
    }
    
    public EventResponse GetEvents(string userName, string password, System.DateTime eventDateTimeStart, System.DateTime eventDateTimeEnd)
    {
        return base.Channel.GetEvents(userName, password, eventDateTimeStart, eventDateTimeEnd);
    }
    
    public System.IAsyncResult BeginGetEvents(string userName, string password, System.DateTime eventDateTimeStart, System.DateTime eventDateTimeEnd, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetEvents(userName, password, eventDateTimeStart, eventDateTimeEnd, callback, asyncState);
    }
    
    public EventResponse EndGetEvents(System.IAsyncResult result)
    {
        return base.Channel.EndGetEvents(result);
    }
    
    public EventResponseByEvent GetEventsByEventCode(string userName, string password, System.DateTime eventDateTimeStart, System.DateTime eventDateTimeEnd, string[] eventCode, int[] actorId)
    {
        return base.Channel.GetEventsByEventCode(userName, password, eventDateTimeStart, eventDateTimeEnd, eventCode, actorId);
    }
    
    public System.IAsyncResult BeginGetEventsByEventCode(string userName, string password, System.DateTime eventDateTimeStart, System.DateTime eventDateTimeEnd, string[] eventCode, int[] actorId, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetEventsByEventCode(userName, password, eventDateTimeStart, eventDateTimeEnd, eventCode, actorId, callback, asyncState);
    }
    
    public EventResponseByEvent EndGetEventsByEventCode(System.IAsyncResult result)
    {
        return base.Channel.EndGetEventsByEventCode(result);
    }
    
    public EventCountResponse VerifyCount(string userName, string password, System.DateTime eventDateTimeStart, System.DateTime eventDateTimeEnd, string[] eventCode, int[] actorId)
    {
        return base.Channel.VerifyCount(userName, password, eventDateTimeStart, eventDateTimeEnd, eventCode, actorId);
    }
    
    public System.IAsyncResult BeginVerifyCount(string userName, string password, System.DateTime eventDateTimeStart, System.DateTime eventDateTimeEnd, string[] eventCode, int[] actorId, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginVerifyCount(userName, password, eventDateTimeStart, eventDateTimeEnd, eventCode, actorId, callback, asyncState);
    }
    
    public EventCountResponse EndVerifyCount(System.IAsyncResult result)
    {
        return base.Channel.EndVerifyCount(result);
    }
    
    public EventResponse GetShipmentStatus(string userName, string password, string number)
    {
        return base.Channel.GetShipmentStatus(userName, password, number);
    }
    
    public System.IAsyncResult BeginGetShipmentStatus(string userName, string password, string number, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetShipmentStatus(userName, password, number, callback, asyncState);
    }
    
    public EventResponse EndGetShipmentStatus(System.IAsyncResult result)
    {
        return base.Channel.EndGetShipmentStatus(result);
    }
}
